/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PepperSupplyChain } from './PepperSupplyChain.js';
export * as factories from './factories/index.js';
export { PepperSupplyChain__factory } from './factories/PepperSupplyChain__factory.js';