/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PepperSupplyChain {
      
    export type LotStruct = {id: BigNumberish, farmId: BytesLike, farmer: AddressLike, owner: AddressLike, initialWeight: BigNumberish, processedWeight: BigNumberish, price: BigNumberish, createdAt: BigNumberish, updatedAt: BigNumberish, status: BigNumberish, flagged: boolean, sourceLots: BigNumberish[]}

    export type LotStructOutput = [id: bigint, farmId: string, farmer: string, owner: string, initialWeight: bigint, processedWeight: bigint, price: bigint, createdAt: bigint, updatedAt: bigint, status: bigint, flagged: boolean, sourceLots: bigint[]] & {id: bigint, farmId: string, farmer: string, owner: string, initialWeight: bigint, processedWeight: bigint, price: bigint, createdAt: bigint, updatedAt: bigint, status: bigint, flagged: boolean, sourceLots: bigint[] }
  
    }

  export interface PepperSupplyChainInterface extends Interface {
    getFunction(nameOrSignature: "admin" | "buyLot" | "certifiers" | "certifyFarm" | "confirmReceived" | "createLot" | "distributors" | "farmers" | "farms" | "flagLot" | "getLot" | "grantCertifier" | "grantDistributor" | "grantFarmer" | "grantProcessor" | "grantRetailer" | "lots" | "markShipped" | "markSold" | "mergeLots" | "processLot" | "processors" | "recallLot" | "retailers" | "revokeDistributor" | "revokeFarmer" | "revokeProcessor" | "revokeRetailer" | "setPrice" | "updateFarmCertification"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuditLog" | "FarmCertified" | "LotCreated" | "LotFlagged" | "LotMerged" | "LotRecalled" | "OwnershipTransferred" | "RoleGranted" | "StatusChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyLot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'certifiers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'certifyFarm', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmReceived', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createLot', values: [BigNumberish, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'farmers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'farms', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'flagLot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantCertifier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantDistributor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantFarmer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantProcessor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRetailer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lots', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markShipped', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markSold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mergeLots', values: [BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'processLot', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'processors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'recallLot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'retailers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeDistributor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeFarmer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeProcessor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRetailer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateFarmCertification', values: [BytesLike, BytesLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certifiers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'certifyFarm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'farmers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'farms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'flagLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantCertifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantDistributor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantProcessor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRetailer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markShipped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markSold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mergeLots', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recallLot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retailers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeDistributor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeProcessor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRetailer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFarmCertification', data: BytesLike): Result;
  }

  
    export namespace AuditLogEvent {
      export type InputTuple = [actor: AddressLike, lotId: BigNumberish, action: BigNumberish];
      export type OutputTuple = [actor: string, lotId: bigint, action: bigint];
      export interface OutputObject {actor: string, lotId: bigint, action: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmCertifiedEvent {
      export type InputTuple = [farmId: BytesLike];
      export type OutputTuple = [farmId: string];
      export interface OutputObject {farmId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LotCreatedEvent {
      export type InputTuple = [lotId: BigNumberish, farmer: AddressLike];
      export type OutputTuple = [lotId: bigint, farmer: string];
      export interface OutputObject {lotId: bigint, farmer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LotFlaggedEvent {
      export type InputTuple = [lotId: BigNumberish];
      export type OutputTuple = [lotId: bigint];
      export interface OutputObject {lotId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LotMergedEvent {
      export type InputTuple = [newLot: BigNumberish];
      export type OutputTuple = [newLot: bigint];
      export interface OutputObject {newLot: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LotRecalledEvent {
      export type InputTuple = [lotId: BigNumberish];
      export type OutputTuple = [lotId: bigint];
      export interface OutputObject {lotId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [lotId: BigNumberish, from: AddressLike, to: AddressLike];
      export type OutputTuple = [lotId: bigint, from: string, to: string];
      export interface OutputObject {lotId: bigint, from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: string, user: AddressLike];
      export type OutputTuple = [role: string, user: string];
      export interface OutputObject {role: string, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StatusChangedEvent {
      export type InputTuple = [lotId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [lotId: bigint, status: bigint];
      export interface OutputObject {lotId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PepperSupplyChain extends BaseContract {
    
    connect(runner?: ContractRunner | null): PepperSupplyChain;
    waitForDeployment(): Promise<this>;

    interface: PepperSupplyChainInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buyLot: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    certifiers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    certifyFarm: TypedContractMethod<
      [farmId: BytesLike, certHash: BytesLike, validUntil: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmReceived: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'view'
    >
    

    
    createLot: TypedContractMethod<
      [id: BigNumberish, farmId: BytesLike, weight: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    distributors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    farmers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    farms: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, boolean] & {certHash: string, validUntil: bigint, certified: boolean }],
      'view'
    >
    

    
    flagLot: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getLot: TypedContractMethod<
      [id: BigNumberish, ],
      [PepperSupplyChain.LotStructOutput],
      'view'
    >
    

    
    grantCertifier: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantDistributor: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantFarmer: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantProcessor: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRetailer: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    lots: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, farmId: string, farmer: string, owner: string, initialWeight: bigint, processedWeight: bigint, price: bigint, createdAt: bigint, updatedAt: bigint, status: bigint, flagged: boolean }],
      'view'
    >
    

    
    markShipped: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    markSold: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mergeLots: TypedContractMethod<
      [newId: BigNumberish, source: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    processLot: TypedContractMethod<
      [id: BigNumberish, processedWeight: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    processors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    recallLot: TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    retailers: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    revokeDistributor: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeFarmer: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeProcessor: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRetailer: TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPrice: TypedContractMethod<
      [id: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateFarmCertification: TypedContractMethod<
      [farmId: BytesLike, newHash: BytesLike, newValid: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buyLot'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'certifiers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'certifyFarm'): TypedContractMethod<
      [farmId: BytesLike, certHash: BytesLike, validUntil: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmReceived'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'createLot'): TypedContractMethod<
      [id: BigNumberish, farmId: BytesLike, weight: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'farmers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'farms'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, bigint, boolean] & {certHash: string, validUntil: bigint, certified: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'flagLot'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLot'): TypedContractMethod<
      [id: BigNumberish, ],
      [PepperSupplyChain.LotStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantCertifier'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantDistributor'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantFarmer'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantProcessor'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRetailer'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lots'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, farmId: string, farmer: string, owner: string, initialWeight: bigint, processedWeight: bigint, price: bigint, createdAt: bigint, updatedAt: bigint, status: bigint, flagged: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'markShipped'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'markSold'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mergeLots'): TypedContractMethod<
      [newId: BigNumberish, source: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'processLot'): TypedContractMethod<
      [id: BigNumberish, processedWeight: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'processors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'recallLot'): TypedContractMethod<
      [id: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retailers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'revokeDistributor'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeFarmer'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeProcessor'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRetailer'): TypedContractMethod<
      [a: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPrice'): TypedContractMethod<
      [id: BigNumberish, price: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFarmCertification'): TypedContractMethod<
      [farmId: BytesLike, newHash: BytesLike, newValid: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuditLog'): TypedContractEvent<AuditLogEvent.InputTuple, AuditLogEvent.OutputTuple, AuditLogEvent.OutputObject>;
getEvent(key: 'FarmCertified'): TypedContractEvent<FarmCertifiedEvent.InputTuple, FarmCertifiedEvent.OutputTuple, FarmCertifiedEvent.OutputObject>;
getEvent(key: 'LotCreated'): TypedContractEvent<LotCreatedEvent.InputTuple, LotCreatedEvent.OutputTuple, LotCreatedEvent.OutputObject>;
getEvent(key: 'LotFlagged'): TypedContractEvent<LotFlaggedEvent.InputTuple, LotFlaggedEvent.OutputTuple, LotFlaggedEvent.OutputObject>;
getEvent(key: 'LotMerged'): TypedContractEvent<LotMergedEvent.InputTuple, LotMergedEvent.OutputTuple, LotMergedEvent.OutputObject>;
getEvent(key: 'LotRecalled'): TypedContractEvent<LotRecalledEvent.InputTuple, LotRecalledEvent.OutputTuple, LotRecalledEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'StatusChanged'): TypedContractEvent<StatusChangedEvent.InputTuple, StatusChangedEvent.OutputTuple, StatusChangedEvent.OutputObject>;

    filters: {
      
      'AuditLog(address,uint256,uint8)': TypedContractEvent<AuditLogEvent.InputTuple, AuditLogEvent.OutputTuple, AuditLogEvent.OutputObject>;
      AuditLog: TypedContractEvent<AuditLogEvent.InputTuple, AuditLogEvent.OutputTuple, AuditLogEvent.OutputObject>;
    

      'FarmCertified(bytes32)': TypedContractEvent<FarmCertifiedEvent.InputTuple, FarmCertifiedEvent.OutputTuple, FarmCertifiedEvent.OutputObject>;
      FarmCertified: TypedContractEvent<FarmCertifiedEvent.InputTuple, FarmCertifiedEvent.OutputTuple, FarmCertifiedEvent.OutputObject>;
    

      'LotCreated(uint256,address)': TypedContractEvent<LotCreatedEvent.InputTuple, LotCreatedEvent.OutputTuple, LotCreatedEvent.OutputObject>;
      LotCreated: TypedContractEvent<LotCreatedEvent.InputTuple, LotCreatedEvent.OutputTuple, LotCreatedEvent.OutputObject>;
    

      'LotFlagged(uint256)': TypedContractEvent<LotFlaggedEvent.InputTuple, LotFlaggedEvent.OutputTuple, LotFlaggedEvent.OutputObject>;
      LotFlagged: TypedContractEvent<LotFlaggedEvent.InputTuple, LotFlaggedEvent.OutputTuple, LotFlaggedEvent.OutputObject>;
    

      'LotMerged(uint256)': TypedContractEvent<LotMergedEvent.InputTuple, LotMergedEvent.OutputTuple, LotMergedEvent.OutputObject>;
      LotMerged: TypedContractEvent<LotMergedEvent.InputTuple, LotMergedEvent.OutputTuple, LotMergedEvent.OutputObject>;
    

      'LotRecalled(uint256)': TypedContractEvent<LotRecalledEvent.InputTuple, LotRecalledEvent.OutputTuple, LotRecalledEvent.OutputObject>;
      LotRecalled: TypedContractEvent<LotRecalledEvent.InputTuple, LotRecalledEvent.OutputTuple, LotRecalledEvent.OutputObject>;
    

      'OwnershipTransferred(uint256,address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RoleGranted(string,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'StatusChanged(uint256,uint8)': TypedContractEvent<StatusChangedEvent.InputTuple, StatusChangedEvent.OutputTuple, StatusChangedEvent.OutputObject>;
      StatusChanged: TypedContractEvent<StatusChangedEvent.InputTuple, StatusChangedEvent.OutputTuple, StatusChangedEvent.OutputObject>;
    
    };
  }